[project]
name = "huffman"
version = "0.1.0"
description = "Huffman Encoder project"
authors = [
    {name = "cfiscella",email = "chris2675@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ds @ git+https://github.com/cfiscella/ds.git"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
